language: node_js
node_js:
    - "16"
before_install:
  - npm i -g npm@8
jobs:
  include:
    - stage: compile
      if: branch != master
      script: npm run build:lib
    - stage: deploy
      if: branch = master
      script: npm run release
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist/docs
        github_token: $GITHUB_TOKEN
        on:
          branch: master