name: Build and Deploy
permissions: read-all
on:
  push:
    branches:
      - master
      - fix/action
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install
        run: yarn
      - name: Build
        run: yarn release
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@5859b4ea7efe6b470a5b19c570460eae9323aefc # v3.2.0
        with:
          target_branch: gh-pages
          build_dir: dist/docs/browser
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
